#!/bin/bash

sleep 5s
URL=https://ooh.tvsimbrasil.com.br/ooh/current-ads
OUTPUT=$(wlr-randr | head -n1 | cut -d' ' -f1)
wlr-randr --output $OUTPUT --transform 90 &
sleep 5s
chromium --kiosk $URL \
        --noerrdialogs \
        --disable-infobars \
        --disable-session-crashed-bubble \
        --disable-translate \
        --no-first-run \
        --fast --fast-start --disable-features=TranslateUI \
        --start-fullscreen \
        --disable-pinch \
        --overscroll-history-navigation=0 \
        --disable-component-update \
        --disable-domain-reliability \
        --safebrowsing-disable-auto-update \
        --disable-client-side-phishing-detection \
        --metrics-recording-only
