#!/bin/bash
exec 1> >(logger -s -t "$(basename "$0")") 2>&1

set -euo pipefail
trap 'echo "Error at line $LINENO"; exit 1' ERR

SLEEP_TIME=10
MAX_TRIES=5

echo "After the internet become connected, the USB ports and Ethernet ports will be disabled..."

echo "Ensuring ssh is enabled..."
sudo systemctl enable --now ssh || { echo "Failed on initialization of SSH. Exiting..."; exit 1; }

while ! ping google.com -c 4 > /dev/null 2>&1; do
    echo "Not connected on internet. Sleeping for 2 seconds..."
    sleep 2
done

# TODO: Awk parse is fragile, but I'm not sure if all usb ports are the same on PI 3b
echo "Disabling USB ports and Ethenet ports..."
(
    sudo uhubctl | awk '/Current status for hub/ {print $5}' | xargs -I {} sudo uhubctl -l {} -p all -a off
) || { echo "Failed on disabling USB and Ethernet ports..."; exit 1; }

for ((i=1; i<=$MAX_TRIES; i++)); do
    cage start_chromium && exit 0
    sleep $SLEEP_TIME
done
echo "Critical failure after $MAX_TRIES attempts" >&2

exit 1