#!/bin/bash
exec 1> >(logger -s -t "$(basename "$0")") 2>&1

set -euo pipefail
trap 'echo "Error at line $LINENO"; exit 1' ERR

sleep 5s
URL=https://ooh.tvsimbrasil.com.br/ooh/current-ads
output=$(wlr-randr | head -n1 | cut -d' ' -f1)

until wlr-randr; do
    echo "Waiting for display connection..."
    sleep 1
done
wlr-randr --output $output --transform 90 &

sleep 5s
(
        chromium --kiosk $URL \
        --noerrdialogs \
        --disable-infobars \
        --disable-session-crashed-bubble \
        --disable-translate \
        --no-first-run \
        --fast --fast-start --disable-features=TranslateUI \
        --start-fullscreen \
        --disable-pinch \
        --overscroll-history-navigation=0 \
        --disable-component-update \
        --disable-domain-reliability \
        --safebrowsing-disable-auto-update \
        --disable-client-side-phishing-detection \
        --metrics-recording-only
) || || { echo "Failed on initialization of chromium. Exiting..."; exit 1; }
