#!/bin/bash
exec 1> >(logger -s -t "$(basename "$0")") 2>&1

set -euo pipefail
trap 'echo "Error at line $LINENO"; exit 1' ERR

username="$USER"
if [[ "$username" != *"-"* ]]; then
    echo "Error: Malformed user name. It should contains '-' and after the numerical identifier."
    exit 1
fi
numeric_part="${username#*-}"
if ! [[ "$numeric_part" =~ ^[0-9]+$ ]]; then
    echo "Error: Part after '-' is not a valid number."
    exit 2
fi

url="https://ooh.tvsimbrasil.com.br/ooh/current-ads?id=$numeric_part"
base="https://ooh.tvsimbrasil.com.br"
sleep 5s
until curl -I $base -c 4 > /dev/null 2>&1; do
    echo "The $url is not available. Sleeping for 20 seconds..."
    sleep 20
done

until wlr-randr; do
    echo "Waiting for display connection..."
    sleep 1
done
output=$(wlr-randr | head -n1 | cut -d' ' -f1)
wlr-randr --output $output --transform 90 &

sleep 5s
chromium --kiosk $url \
        --noerrdialogs \
        --disable-infobars \
        --disable-session-crashed-bubble \
        --disable-translate \
        --no-first-run \
        --fast --fast-start --disable-features=TranslateUI \
        --start-fullscreen \
        --disable-pinch \
        --overscroll-history-navigation=0 \
        --disable-component-update \
        --disable-domain-reliability \
        --safebrowsing-disable-auto-update \
        --disable-client-side-phishing-detection \
        --metrics-recording-only \
        || { echo "Failed on initialization of chromium. Exiting..."; exit 1; }
